# .github/workflows/deploy.yml
name: Deploy React App to EC2

on:
  push:
    branches: [ main ]  # main 브랜치 push 시 작동

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install dependencies and build
      env:
        REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
      run: |
        yarn install
        CI=false yarn build

    - name: Compress build files
      run: tar -czf build.tar.gz build/

    - name: Copy build to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "build.tar.gz"
        target: "~/react-app"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/react-app
          tar -xzf build.tar.gz
          rm -rf current
          mv build current
          # 예: serve 설치 후 실행
          sudo pkill -f "npx serve -s current" || true
          sudo nohup npx serve -s current -l 5173 > serve.log 2>&1 &

          echo "Waiting for server to be healthy..."
          for i in {1..5}; do
            sleep 2
            if curl -sSf http://localhost:5173 > /dev/null; then
              echo "✅ Health check passed!"
              exit 0
            else
              echo "⏳ Waiting for app... attempt $i"
            fi
          done

          echo "❌ Health check failed after 5 attempts"
          exit 1
